// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GameSystem {

  /// <summary>Holder for reflection information generated from Config.proto</summary>
  public static partial class ConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for Config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxDb25maWcucHJvdG8SCkdhbWVTeXN0ZW0ihAIKB1Rlc3RNc2cSDQoFdGVz",
            "dEYYASABKAISDQoFdGVzdEQYAiABKAESEAoIdGVzdFNJbnQYAyABKBESEQoJ",
            "dGVzdFVMb25nGAQgASgEEhAKCHRlc3RCb29sGAUgASgIEhIKCnRlc3RTdHJp",
            "bmcYBiABKAkSFwoPdGVzdEJ5dGVzU3RyaW5nGAcgASgMEhQKDHRlc3RMaXN0",
            "U0ludBgIIAMoERIxCgd0ZXN0TWFwGAkgAygLMiAuR2FtZVN5c3RlbS5UZXN0",
            "TXNnLlRlc3RNYXBFbnRyeRouCgxUZXN0TWFwRW50cnkSCwoDa2V5GAEgASgR",
            "Eg0KBXZhbHVlGAIgASgJOgI4ASofCghUZXN0RW51bRIICgROb25lEAASCQoF",
            "VGVzdDEQBGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GameSystem.TestEnum), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GameSystem.TestMsg), global::GameSystem.TestMsg.Parser, new[]{ "TestF", "TestD", "TestSInt", "TestULong", "TestBool", "TestString", "TestBytesString", "TestListSInt", "TestMap" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Enums
  public enum TestEnum {
    /// <summary>
    /// 第一个必须映射到0
    /// </summary>
    [pbr::OriginalName("None")] None = 0,
    [pbr::OriginalName("Test1")] Test1 = 4,
  }

  #endregion

  #region Messages
  /// <summary>
  /// 类型
  /// 浮点数 float double
  /// 变长编码 int32 int64 sint32 sint64 uint32 uint64
  /// int32 int64的效率低，建议使用 sint32 sint64
  /// 固定长度 fixed32 fixed64 sfixed32 sfixed64
  /// 表示大数时更高效
  /// 其他 bool string bytes(字节字符串)
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TestMsg : pb::IMessage<TestMsg>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TestMsg> _parser = new pb::MessageParser<TestMsg>(() => new TestMsg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TestMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameSystem.ConfigReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestMsg(TestMsg other) : this() {
      testF_ = other.testF_;
      testD_ = other.testD_;
      testSInt_ = other.testSInt_;
      testULong_ = other.testULong_;
      testBool_ = other.testBool_;
      testString_ = other.testString_;
      testBytesString_ = other.testBytesString_;
      testListSInt_ = other.testListSInt_.Clone();
      testMap_ = other.testMap_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TestMsg Clone() {
      return new TestMsg(this);
    }

    /// <summary>Field number for the "testF" field.</summary>
    public const int TestFFieldNumber = 1;
    private float testF_;
    /// <summary>
    /// 字段 类型 + 唯一编号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float TestF {
      get { return testF_; }
      set {
        testF_ = value;
      }
    }

    /// <summary>Field number for the "testD" field.</summary>
    public const int TestDFieldNumber = 2;
    private double testD_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double TestD {
      get { return testD_; }
      set {
        testD_ = value;
      }
    }

    /// <summary>Field number for the "testSInt" field.</summary>
    public const int TestSIntFieldNumber = 3;
    private int testSInt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TestSInt {
      get { return testSInt_; }
      set {
        testSInt_ = value;
      }
    }

    /// <summary>Field number for the "testULong" field.</summary>
    public const int TestULongFieldNumber = 4;
    private ulong testULong_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong TestULong {
      get { return testULong_; }
      set {
        testULong_ = value;
      }
    }

    /// <summary>Field number for the "testBool" field.</summary>
    public const int TestBoolFieldNumber = 5;
    private bool testBool_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool TestBool {
      get { return testBool_; }
      set {
        testBool_ = value;
      }
    }

    /// <summary>Field number for the "testString" field.</summary>
    public const int TestStringFieldNumber = 6;
    private string testString_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TestString {
      get { return testString_; }
      set {
        testString_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "testBytesString" field.</summary>
    public const int TestBytesStringFieldNumber = 7;
    private pb::ByteString testBytesString_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString TestBytesString {
      get { return testBytesString_; }
      set {
        testBytesString_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "testListSInt" field.</summary>
    public const int TestListSIntFieldNumber = 8;
    private static readonly pb::FieldCodec<int> _repeated_testListSInt_codec
        = pb::FieldCodec.ForSInt32(66);
    private readonly pbc::RepeatedField<int> testListSInt_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> TestListSInt {
      get { return testListSInt_; }
    }

    /// <summary>Field number for the "testMap" field.</summary>
    public const int TestMapFieldNumber = 9;
    private static readonly pbc::MapField<int, string>.Codec _map_testMap_codec
        = new pbc::MapField<int, string>.Codec(pb::FieldCodec.ForSInt32(8, 0), pb::FieldCodec.ForString(18, ""), 74);
    private readonly pbc::MapField<int, string> testMap_ = new pbc::MapField<int, string>();
    /// <summary>
    /// namesapce.TypeName fileName = id; 使用其他命名空间的类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, string> TestMap {
      get { return testMap_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TestMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TestMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(TestF, other.TestF)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(TestD, other.TestD)) return false;
      if (TestSInt != other.TestSInt) return false;
      if (TestULong != other.TestULong) return false;
      if (TestBool != other.TestBool) return false;
      if (TestString != other.TestString) return false;
      if (TestBytesString != other.TestBytesString) return false;
      if(!testListSInt_.Equals(other.testListSInt_)) return false;
      if (!TestMap.Equals(other.TestMap)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TestF != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(TestF);
      if (TestD != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(TestD);
      if (TestSInt != 0) hash ^= TestSInt.GetHashCode();
      if (TestULong != 0UL) hash ^= TestULong.GetHashCode();
      if (TestBool != false) hash ^= TestBool.GetHashCode();
      if (TestString.Length != 0) hash ^= TestString.GetHashCode();
      if (TestBytesString.Length != 0) hash ^= TestBytesString.GetHashCode();
      hash ^= testListSInt_.GetHashCode();
      hash ^= TestMap.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TestF != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(TestF);
      }
      if (TestD != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(TestD);
      }
      if (TestSInt != 0) {
        output.WriteRawTag(24);
        output.WriteSInt32(TestSInt);
      }
      if (TestULong != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(TestULong);
      }
      if (TestBool != false) {
        output.WriteRawTag(40);
        output.WriteBool(TestBool);
      }
      if (TestString.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(TestString);
      }
      if (TestBytesString.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(TestBytesString);
      }
      testListSInt_.WriteTo(output, _repeated_testListSInt_codec);
      testMap_.WriteTo(output, _map_testMap_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TestF != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(TestF);
      }
      if (TestD != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(TestD);
      }
      if (TestSInt != 0) {
        output.WriteRawTag(24);
        output.WriteSInt32(TestSInt);
      }
      if (TestULong != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(TestULong);
      }
      if (TestBool != false) {
        output.WriteRawTag(40);
        output.WriteBool(TestBool);
      }
      if (TestString.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(TestString);
      }
      if (TestBytesString.Length != 0) {
        output.WriteRawTag(58);
        output.WriteBytes(TestBytesString);
      }
      testListSInt_.WriteTo(ref output, _repeated_testListSInt_codec);
      testMap_.WriteTo(ref output, _map_testMap_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TestF != 0F) {
        size += 1 + 4;
      }
      if (TestD != 0D) {
        size += 1 + 8;
      }
      if (TestSInt != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(TestSInt);
      }
      if (TestULong != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TestULong);
      }
      if (TestBool != false) {
        size += 1 + 1;
      }
      if (TestString.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TestString);
      }
      if (TestBytesString.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(TestBytesString);
      }
      size += testListSInt_.CalculateSize(_repeated_testListSInt_codec);
      size += testMap_.CalculateSize(_map_testMap_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TestMsg other) {
      if (other == null) {
        return;
      }
      if (other.TestF != 0F) {
        TestF = other.TestF;
      }
      if (other.TestD != 0D) {
        TestD = other.TestD;
      }
      if (other.TestSInt != 0) {
        TestSInt = other.TestSInt;
      }
      if (other.TestULong != 0UL) {
        TestULong = other.TestULong;
      }
      if (other.TestBool != false) {
        TestBool = other.TestBool;
      }
      if (other.TestString.Length != 0) {
        TestString = other.TestString;
      }
      if (other.TestBytesString.Length != 0) {
        TestBytesString = other.TestBytesString;
      }
      testListSInt_.Add(other.testListSInt_);
      testMap_.MergeFrom(other.testMap_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 13: {
            TestF = input.ReadFloat();
            break;
          }
          case 17: {
            TestD = input.ReadDouble();
            break;
          }
          case 24: {
            TestSInt = input.ReadSInt32();
            break;
          }
          case 32: {
            TestULong = input.ReadUInt64();
            break;
          }
          case 40: {
            TestBool = input.ReadBool();
            break;
          }
          case 50: {
            TestString = input.ReadString();
            break;
          }
          case 58: {
            TestBytesString = input.ReadBytes();
            break;
          }
          case 66:
          case 64: {
            testListSInt_.AddEntriesFrom(input, _repeated_testListSInt_codec);
            break;
          }
          case 74: {
            testMap_.AddEntriesFrom(input, _map_testMap_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 13: {
            TestF = input.ReadFloat();
            break;
          }
          case 17: {
            TestD = input.ReadDouble();
            break;
          }
          case 24: {
            TestSInt = input.ReadSInt32();
            break;
          }
          case 32: {
            TestULong = input.ReadUInt64();
            break;
          }
          case 40: {
            TestBool = input.ReadBool();
            break;
          }
          case 50: {
            TestString = input.ReadString();
            break;
          }
          case 58: {
            TestBytesString = input.ReadBytes();
            break;
          }
          case 66:
          case 64: {
            testListSInt_.AddEntriesFrom(ref input, _repeated_testListSInt_codec);
            break;
          }
          case 74: {
            testMap_.AddEntriesFrom(ref input, _map_testMap_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
